
#' Adiciona rotulos descritivos a partir de colunas de codigos
#'
#' @description Cria colunas de rotulos associada a colunas de codigos.
#'
#' @param data DataFrame.
#' @param type_data String. O tipo da base de dados do CNES que sera baixado. Valores aceitos ("cnes", "leitos", "equipamentos", "habilitacao").
#'
#' @return O DataFrame recebido e as novas colunas.
#'
#' @examples
#' \dontrun{
#'   data = labels(data, "cnes" )
#' }
#'
#' @export
labels = function(data, type_data){

  type_data = tolower(trimws(type_data))

  if (type_data == "cnes") {
    #ADD a coluna com o nome dos Hospitais
    data = data %>%
      dplyr::mutate(
        Nome_CNES = dplyr::case_match(
          CNES,
          "0" ~ NA,
          "0000396" ~ "HC da Univ. Federal de Pernambuco (HC-UFPE)",
          "0002534" ~ "HU da Universidade Federal de Sergipe (HU-UFS)",
          "0003816" ~ "HU Professor Edgard Santos (Hupes-UFBA)",
          "0004731" ~ "Maternidade Clim\u00e9rio de Oliveira (MCO-UFBA)",
          "0009709" ~ "HU Maria Aparecida Pedrossian (Humap-UFMS)",
          "0010510" ~ "HU da Universidade de Bras\u00edlia (HUB-UnB)",
          "0012505" ~ "HU Ant\u00f4nio Pedro (HUAP-UFF)",
          "0027049" ~ "HC da Univ. Federal de Minas Gerais (HC-UFMG)",
          "2006197" ~ "HU Professor Alberto Antunes (HUPAA-UFAL)",
          "2017644" ~ "HU Get\u00falio Vargas (HUGV-UFAM)",
          "2146339" ~ "Ambulat\u00f3rio Am\u00e9lio Marques (AAM-HC-UFU)",
          "2146355" ~ "Hospital de Cl\u00ednicas de Uberl\u00e2ndia (HC-UFU)",
          "2146371" ~ "Unidade Di\u00e1lise Hemodi\u00e1lise (UDH-HC-UFU)",
          "2206595" ~ "HC da Univ. Feder. do Tri\u00e2ngulo Mineiro (HC-UFTM)",
          "2218798" ~ "HU da Univ. Federal de Juiz de Fora (HU-UFJF)",
          "2244306" ~ "HU da Univ. Federal de Santa Maria (HUSM-UFSM)",
          "2252694" ~ "HE da Univ. Federal de Pelotas (HE-UFPel)",
          "2295415" ~ "HU Gaffree e Guinle (HUGG-Unirio)",
          "2332981" ~ "HU Jo\u00e3o de Barros Barreto (HUJBB-UFPA)",
          "2338424" ~ "HC da Universidade Federal de Goi\u00e1s (HC-UFG)",
          "2384299" ~ "Complexo do HC da Univ.Fed. do Paran\u00e1 (CHC-UFPR)",
          "2400243" ~ "HU Lauro Wanderley (HULW-UFPB)",
          "2409208" ~ "Maternidade Escola Janu\u00e1rio Cicco (Mejc-UFRN)",
          "2481286" ~ "Maternidade Escola Assis Chateaubriand (Meac-UFC)",
          "2504502" ~ "HU J\u00falio Maria Bandeira de Mello (HUJB-UFCG)",
          "2561492" ~ "HU Walter Cant\u00eddio (HUWC-UFC)",
          "2640244" ~ "Maternidade Victor F. do Amaral (MVFA-UFPR)",
          "2653982" ~ "Hospital Universit\u00e1rio Onofre Lopes (Huol-UFRN)",
          "2655411" ~ "Hospital Universit\u00e1rio J\u00falio Muller (HUJM-UFMT)",
          "2676060" ~ "Hospital Universit\u00e1rio Alcides Carneiro (HUAC-UFCG)",
          "2694751" ~ "HU Bettina Ferro de Souza (HUBFS-UFPA)",
          "2707675" ~ "HU Dr. Miguel Riet Correa Junior (HU-Furg)",
          "2710935" ~ "HU da Univ. Federal da Grande Dourados (HU-UFGD)",
          "2726653" ~ "HU da Universidade Federal do Maranh\u00e3o (HU-UFMA)",
          "3157245" ~ "HU da Univ. Federal de Santa Catarina (HU-UFSC)",
          "3285391" ~ "HU da Universidade Federal do Piau\u00ed (HU-UFPI)",
          "3432076" ~ "HU da Universidade Federal do Amap\u00e1 (HU-Unifap)",
          "3654826" ~ "Hospital de Doen\u00e7as Tropicais (HDT-UFT)",
          "4014111" ~ "Hospital Universit\u00e1rio Ana Bezerra (Huab-UFRN)",
          "4044916" ~ "HU Cassiano Ant\u00f4nio Moraes (Hucam-UFES)",
          "5586348" ~ "HU da Univ. Federal de S\u00e3o Carlos (HU-Ufscar)",
          "6042414" ~ "HU da Univ. Fed. Vale do S\u00e3o Francisco (HU-Univasf)",
          "6568343" ~ "Hospital Universit\u00e1rio de Lagarto (HUL-UFS)",
          .default = CNES
        )
      ) %>% dplyr::relocate(Nome_CNES, .before = 4)
  }
  if (type_data == "leitos") {
    data = data %>%
      dplyr::mutate(
        Nome_TP_LEITO = dplyr::case_match(
          TP_LEITO,
          "1" ~ "Cir\u00fargico",
          "2" ~ "Cl\u00ednico",
          "3" ~ "Complementar",
          "4" ~ "Obst\u00e9trico",
          "5" ~ "Pedi\u00e1trico",
          "6" ~ "Outras Especialidades",
          .default = TP_LEITO
        )
      ) %>% dplyr::relocate(Nome_TP_LEITO, .before = 5)
  }
  if (type_data == "equipamentos") {
    data <- data %>%
      dplyr::mutate(
        Nome_Tipo_Equipamento = dplyr::case_match(
          Tipo_Equipamento,
          "1" ~ "Equipamentos De Diagnostico Por Imagem",
          "2" ~ "Equipamentos De Infra-Estrutura",
          "3" ~ "Equipamentos Por M\u00e9todos \u00d3pticos",
          "4" ~ "Equipamentos Por M\u00e9todos Gr\u00e1ficos",
          "5" ~ "Equipamentos Para Manuten\u00e7\u00e3o Da Vida",
          "6" ~ "Outros Equipamentos",
          "7" ~ "Equipamentos De Odontologia",
          "8" ~ "Equipamentos De Audiologia",
          "9" ~ "Equipamentos De Telessa\u00fade",
          .default = Tipo_Equipamento
        )
      ) %>% dplyr::relocate(Nome_Tipo_Equipamento, .before = 5)

    data <- data %>%
      dplyr::mutate(
        Nome_Equipamento = dplyr::case_match(
          Cod_Equipamento,
          "01" ~ "Gama C\u00e2mara",
          "02" ~ "Mam\u00f3grafo com Comando Simples",
          "03" ~ "Mam\u00f3grafo com Estereotaxia",
          "04" ~ "Raio X At\u00e9 100 Ma",
          "05" ~ "Raio X de 100 A 500 Ma",
          "06" ~ "Raio X Mais de 500ma",
          "07" ~ "Raio X Dent\u00e1rio",
          "08" ~ "Raio X com Fluoroscopia",
          "09" ~ "Raio X para Densitometria \u00d3ssea",
          "10" ~ "Raio X para Hemodin\u00e2mica",
          "11" ~ "Tom\u00f3grafo Computadorizado",
          "12" ~ "Resson\u00e2ncia Magn\u00e9tica",
          "13" ~ "Ultrassom Doppler Colorido",
          "14" ~ "Ultrassom Ec\u00f3grafo",
          "15" ~ "Ultrassom Convencional",
          "16" ~ "Processadora de Filme Exclusiva Para Mamografia",
          "17" ~ "Mam\u00f3grafo Computadorizado",
          "18" ~ "PET/CT",
          "19" ~ "Ar Condicionado",
          "20" ~ "Camera Frigorifica",
          "21" ~ "Controle Ambiental/Ar-condicionado Central",
          "22" ~ "Grupo Gerador",
          "23" ~ "Usina de Oxig\u00eanio",
          "24" ~ "Camara para Conserva\u00e7\u00e3o de Hemoderivados/Imuno/Termolabeis",
          "25" ~ "Camara para Conserva\u00e7\u00e3o de Imunobiologicos",
          "26" ~ "Condensador",
          "27" ~ "Freezer Cient\u00edfico",
          "28" ~ "Grupo Gerador (101 A 300 KVA)",
          "29" ~ "Grupo Gerador (8 A 100 KVA)",
          "30" ~ "Grupo Gerador (Acima de 300 KVA)",
          "31" ~ "Endosc\u00f3pio das Vias Respirat\u00f3rias",
          "32" ~ "Endosc\u00f3pio das Vias Urinarias",
          "33" ~ "Endosc\u00f3pio Digestivo",
          "34" ~ "Equipamentos para Optometria",
          "35" ~ "Laparosc\u00f3pico/V\u00eddeo",
          "36" ~ "Microsc\u00f3pio Cir\u00fargico",
          "37" ~ "Cadeira Oftalmol\u00f3gica",
          "38" ~ "Coluna Oftalmol\u00f3gica",
          "39" ~ "Refrator",
          "40" ~ "Lensometro",
          "41" ~ "Eletrocardi\u00f3grafo",
          "42" ~ "Eletroencefal\u00f3grafo",
          "43" ~ "Grupo Gerador de 1.500 (m\u00ednimo)",
          "44" ~ "Projetor ou Tabela de Optotipos",
          "45" ~ "Retinosc\u00f3pio",
          "46" ~ "Oftalmosc\u00f3pio",
          "47" ~ "Ceratometro",
          "48" ~ "Ton\u00f4metro de Aplana\u00e7\u00e3o",
          "49" ~ "Biomicroscopio (L\u00e2mpada de Fenda)",
          "50" ~ "Campimetro",
          "51" ~ "Bomba/Bal\u00e3o Intra-a\u00f3rtico",
          "52" ~ "Bomba de Infus\u00e3o",
          "53" ~ "Ber\u00e7o Aquecido",
          "54" ~ "Bilirrubinometro",
          "55" ~ "Debit\u00f4metro",
          "56" ~ "Desfibrilador",
          "57" ~ "Equipamento de Fototerapia",
          "58" ~ "Incubadora",
          "59" ~ "Marca-passo Tempor\u00e1rio",
          "60" ~ "Monitor de ECG",
          "61" ~ "Monitor de Press\u00e3o Invasivo",
          "62" ~ "Monitor de Press\u00e3o N\u00e3o Invasivo",
          "63" ~ "Reanimador Pulmonar/Ambu",
          "64" ~ "Respirador/Ventilador",
          "65" ~ "Grupo Gerador Port\u00e1til (at\u00e9 7 KVA)",
          "66" ~ "Refrigerador",
          "67" ~ "Caminh\u00e3o Ba\u00fa Refrigerado",
          "68" ~ "Embarca\u00e7\u00e3o para Transporte com Motor Popa (at\u00e9 12 pessoas)",
          "69" ~ "Empilhadeira",
          "70" ~ "Ve\u00edculo Utilit\u00e1rio (Tipo Furg\u00e3o)",
          "71" ~ "Aparelho de Diatermia por Ultrassom/Ondas Curtas",
          "72" ~ "Aparelho de Eletroestimula\u00e7\u00e3o",
          "73" ~ "Bomba de Infus\u00e3o de Hemoderivados",
          "74" ~ "Equipamentos de Af\u00e9rese",
          "75" ~ "Equipamento de Circula\u00e7\u00e3o Extracorp\u00f3rea",
          "76" ~ "Equipamento Para Hemodi\u00e1lise",
          "77" ~ "Forno de Bier",
          "78" ~ "Ve\u00edculo Pick-up Cabine Dupla 4x4 (Diesel)",
          "79" ~ "Equipo Odontol\u00f3gico Completo",
          "80" ~ "Compressor Odontol\u00f3gico",
          "81" ~ "Fotopolimerizador",
          "82" ~ "Caneta de Alta Rota\u00e7\u00e3o",
          "83" ~ "Caneta de Baixa Rota\u00e7\u00e3o",
          "84" ~ "Amalgamador",
          "85" ~ "Aparelho de Profilaxia C/Jato de Bicarbonato",
          "86" ~ "Emiss\u00f5es Otoac\u00fasticas Evocadas Transientes",
          "87" ~ "Emiss\u00f5es Otoac\u00fasticas Evocadas por Produto de Distor\u00e7\u00e3o",
          "88" ~ "Potencial Evocado Auditivo de Tronco Encef\u00e1lico Autom\u00e1tico",
          "89" ~ "Pot Evocado Aud Tronco Encef de Curta, Media e Longa Lat\u00eancia",
          "90" ~ "Audi\u00f4metro de Um Canal",
          "91" ~ "Audi\u00f4metro de Dois Canais",
          "92" ~ "Imitanciometro",
          "93" ~ "Imitanciometro Multifrequencial",
          "94" ~ "Cabine Ac\u00fastica",
          "95" ~ "Sistema de Campo Livre",
          "96" ~ "Sistema Completo de Refor\u00e7o Visual (VRA)",
          "97" ~ "Ganho de Inser\u00e7\u00e3o",
          "98" ~ "Hi-Pro",
          .default = Cod_Equipamento
        )
      ) %>% dplyr::relocate(Nome_Equipamento, .before = 7)
  }
  if (type_data == "habilitacao") {
    data = data %>%
      dplyr::mutate(
        Nome_Habilitacao = dplyr::case_match(
          Cod_Habilitacao,
          "0" ~ NA,
          "0101" ~ "Centro ref aten\u00e7\u00e3o \u00e0 saude idoso",
          "0201" ~ "Centro ref cirurgia bariatrica",
          "0301" ~ "Centros/nucleos realiz implante coclear",
          "0302" ~ "Diagn/trat/reabil auditiva media complexidade",
          "0303" ~ "Diagn/trat/reabil auditiva alta complexidade",
          "0401" ~ "Centro tratamento m\u00e1 forma\u00e7\u00e3o l\u00e1bio palatal",
          "0402" ~ "Laborat\u00f3rio regional pr\u00f3tese dent\u00e1ria",
          "0403" ~ "Centro especialidades odontol\u00f3gicas I",
          "0404" ~ "Centro especialidades odontol\u00f3gicas II",
          "0405" ~ "Centro especialidades odontol\u00f3gicas III",
          "0501" ~ "Centro ref em oftalmologia n\u00edvel I",
          "0502" ~ "Centro ref em oftalmologia n\u00edvel II",
          "0601" ~ "Aten\u00e7\u00e3o \u00e0 sa\u00fade mental - classe I",
          "0602" ~ "Aten\u00e7\u00e3o \u00e0 sa\u00fade mental - classe II",
          "0603" ~ "Aten\u00e7\u00e3o \u00e0 sa\u00fade mental - classe III",
          "0604" ~ "Aten\u00e7\u00e3o \u00e0 sa\u00fade mental - classe IV",
          "0605" ~ "Aten\u00e7\u00e3o \u00e0 sa\u00fade mental - classe V",
          "0606" ~ "Aten\u00e7\u00e3o \u00e0 sa\u00fade mental - classe VI",
          "0607" ~ "Aten\u00e7\u00e3o \u00e0 sa\u00fade mental - classe VII",
          "0608" ~ "Aten\u00e7\u00e3o \u00e0 sa\u00fade mental - classe VIII",
          "0609" ~ "Aten\u00e7\u00e3o \u00e0 sa\u00fade mental - classe IX",
          "0610" ~ "Aten\u00e7\u00e3o \u00e0 sa\u00fade mental - classe X",
          "0611" ~ "Aten\u00e7\u00e3o \u00e0 sa\u00fade mental - classe XI",
          "0612" ~ "Aten\u00e7\u00e3o \u00e0 sa\u00fade mental - classe XII",
          "0613" ~ "Aten\u00e7\u00e3o \u00e0 sa\u00fade mental - classe XIII",
          "0614" ~ "Aten\u00e7\u00e3o \u00e0 sa\u00fade mental - classe XIV",
          "0615" ~ "PNASS maior que 80%",
          "0616" ~ "CAPS I",
          "0617" ~ "CAPS II",
          "0618" ~ "CAPS III",
          "0619" ~ "CAPS \u00e1lcool e drogas",
          "0620" ~ "CAPS infantil",
          "0621" ~ "Serv hosp ref usu\u00e1rios \u00e1lcool/drogas",
          "0622" ~ "Serv hosp ref usu\u00e1rios \u00e1lcool/drogas classe I",
          "0623" ~ "Serv hosp ref usu\u00e1rios \u00e1lcool/drogas classe II",
          "0624" ~ "Serv hosp ref usu\u00e1rios \u00e1lcool/drogas classe III",
          "0625" ~ "Serv hosp ref usu\u00e1rios \u00e1lcool/drogas classe IV",
          "0626" ~ "Serv hosp ref usu\u00e1rios \u00e1lcool/drogas classe V",
          "0627" ~ "Serv hosp ref usu\u00e1rios \u00e1lcool/drogas classe VI",
          "0628" ~ "Serv hosp ref usu\u00e1rios \u00e1lcool/drogas classe VII",
          "0629" ~ "Serv hosp ref usu\u00e1rios \u00e1lcool/drogas classe VIII",
          "0630" ~ "Psiquiatria III",
          "0701" ~ "Servi\u00e7o ref sa\u00fade trabalhador estadual A",
          "0702" ~ "Servi\u00e7o ref sa\u00fade trabalhador estadual B",
          "0703" ~ "Servi\u00e7o ref sa\u00fade trabalhador estadual C",
          "0704" ~ "Servi\u00e7o ref sa\u00fade trabalhador regional A",
          "0705" ~ "Servi\u00e7o ref sa\u00fade trabalhador regional B",
          "0706" ~ "Servi\u00e7o ref sa\u00fade trabalhador regional C",
          "0801" ~ "Unid assist alta complexidade cardiovascular",
          "0802" ~ "Centro ref alta complexidade cardiovascular",
          "0803" ~ "Cir cardiov, proc cardiolog intervencionista",
          "0804" ~ "Cirurgia cardiovascular pedi\u00e1trica",
          "0805" ~ "Cirurgia vascular",
          "0806" ~ "Cirurgia vascular, proc endovasc extracard\u00edacos",
          "0807" ~ "Lab eletrof, cir cardio, proc cardio interv",
          "0808" ~ "Implante marcapasso definitivo",
          "0809" ~ "Cirurgia card\u00edaca",
          "0810" ~ "Lab.eletrofisiol/terapia intervencionista",
          "1001" ~ "Centro refer\u00eancia tratamento dor cr\u00f4nica",
          "1101" ~ "Servi\u00e7o hospitalar para tratamento AIDS",
          "1102" ~ "Laboratorio para cd4/cd8, carga viral",
          "1103" ~ "Tratam. lipoatrofia facial portador HIV/AIDS",
          "1104" ~ "Tratamento lipodistrofia portador HIV/AIDS",
          "1201" ~ "Fibrose c\u00edstica hospital dia",
          "1202" ~ "Proc cirurg diagnost/terapeut hospital dia",
          "1203" ~ "Hospital dia - AIDS",
          "1204" ~ "Hosp.dia intercorr postranspl.med.ossea/outr",
          "1205" ~ "Hospital dia - geriatria",
          "1206" ~ "Hospital dia - saude mental",
          "1401" ~ "Ref hospit atend secund gestante alto risco",
          "1402" ~ "Ref hospit atend terc gestante alto risco",
          "1403" ~ "Unid realiza assist ao parto s/dist.p/enferm",
          "1404" ~ "Hospital amigo crian\u00e7a",
          "1405" ~ "Cent ref triag neonat/acomp doen\u00e7a congenita",
          "1406" ~ "Cent ref triag neonat/acomp doen\u00e7 falciforme",
          "1407" ~ "Cent ref triag neonat/acomp fibrose c\u00edstica",
          "1501" ~ "Unidade assist alta complexidade nefrologia",
          "1502" ~ "Centro ref alta complexidade nefrologia",
          "1503" ~ "Hemodi\u00e1lise II",
          "1601" ~ "Unid.assist alta complexidade neurol/neurocirurg",
          "1602" ~ "Centro ref alta complexidade neurol/neurocirurg",
          "1603" ~ "Trauma e anomalias desenvolvimento",
          "1604" ~ "Coluna e dos nervos perif\u00e9ricos",
          "1605" ~ "Tumores sistema nervoso",
          "1606" ~ "Neurocirurgia vascular",
          "1607" ~ "Trat.neurocirurgico dor/funcional",
          "1608" ~ "Investiga\u00e7\u00e3o e cirurgia epilepsia",
          "1609" ~ "Tratamento neuro endovascular",
          "1610" ~ "Neurocirurgia funcional esteriot\u00e1xica",
          "1611" ~ "Epilepsia",
          "1612" ~ "Neurocirurgia I",
          "1613" ~ "Neurocirurgia II",
          "1614" ~ "Neurocirurgia III",
          "1701" ~ "Centro alta complexidade oncologia CACON I",
          "1702" ~ "Centro alta complexidade oncologia CACON II",
          "1703" ~ "Centro alta complexidade oncologia CACON III",
          "1704" ~ "Servi\u00e7o isolado radioterapia",
          "1705" ~ "Servi\u00e7o isolado quimioterapia",
          "1706" ~ "UNACON",
          "1707" ~ "UNACON com servi\u00e7o de radioterapia",
          "1708" ~ "UNACON com servi\u00e7o de hematologia",
          "1709" ~ "UNACON com servi\u00e7o de oncologia pedi\u00e1trica",
          "1710" ~ "UNACON exclusiva de hematologia",
          "1711" ~ "UNACON exclusiva de oncologia pedi\u00e1trica",
          "1712" ~ "CACON",
          "1713" ~ "CACON com servi\u00e7o de oncologia pedi\u00e1trica",
          "1714" ~ "Hospital geral com cirurgia oncol\u00f3gica",
          "1801" ~ "Centro ref tratam.osteogenesis imperfecta",
          "2001" ~ "Prog assist ventilat\u00f3ria n\u00e3o invasiva distr musc",
          "2101" ~ "Centro ref assist queimados m\u00e9dia complexidade",
          "2102" ~ "Centro ref assist queimados alta complexidade",
          "2201" ~ "Centro ref reabilita\u00e7\u00e3o medicina f\u00edsica",
          "2202" ~ "Servi\u00e7o reabilit f\u00edsica n\u00edvel intermedi\u00e1rio",
          "2301" ~ "Unid.assist alta complexidade terapia nutricional",
          "2302" ~ "Centro ref alta complexidade terap nutricional",
          "2303" ~ "Centro ref terap nutricional Enteral",
          "2304" ~ "Centro ref terap nutric enteral e parenteral",
          "2305" ~ "Cent ref terap nut ent/parent-manipul,fabric",
          "2306" ~ "Nutri\u00e7ao enteral",
          "2401" ~ "Transpl.medula \u00f3ssea autog\u00eanico",
          "2402" ~ "Transpl.medula \u00f3ssea alog\u00eanico aparentado",
          "2403" ~ "Transpl.medula \u00f3ssea alog\u00eanico n\u00e3o aparentado",
          "2404" ~ "Transplante de p\u00e2ncreas isolado",
          "2405" ~ "Transplante de conjugado rim e p\u00e2ncreas",
          "2407" ~ "Transplante de c\u00f3rnea/esclera",
          "2408" ~ "Transplante de rim",
          "2409" ~ "Transplante de f\u00edgado",
          "2410" ~ "Transplante de pulm\u00e3o",
          "2411" ~ "Transplante de cora\u00e7\u00e3o",
          "2412" ~ "Busca ativa \u00f3rg\u00e3os",
          "2413" ~ "Banco tecido ocular humano",
          "2414" ~ "Banco v\u00e1lvulas card\u00edacas",
          "2415" ~ "Banco tecido m\u00fasculo esquel\u00e9tico",
          "2416" ~ "Banco sangue/cord\u00e3o umbilical/placent\u00e1rio",
          "2417" ~ "Ex.histocompatibilidade sorol tipo I",
          "2418" ~ "Ex.histocompat.sorol/biologia molecular II",
          "2501" ~ "Unid.assist alta complexidade traumato-ortopedia",
          "2502" ~ "Centro ref alta complexidade traumato-ortopedia",
          "2503" ~ "Centro ref traumato-ortopedia Coluna",
          "2504" ~ "Cent ref cint escapular/ombro/braco/cotovelo",
          "2505" ~ "Cent ref traum-ortop antebraco, punho e m\u00e3o",
          "2506" ~ "Cent ref traum-ort cint p\u00e9lvica/quadril/coxa",
          "2507" ~ "Cent ref traumato-ortop coxa, joelho e perna",
          "2508" ~ "Cent ref traumato-ortop perna, tornozelo, p\u00e9",
          "2509" ~ "Cent ref traumato-ortopedia infantil",
          "2510" ~ "Cent ref Traumatologia ortop\u00e9dica urg\u00eancia",
          "2511" ~ "Ortopedia - coluna",
          "2512" ~ "Ortopedia - ombro",
          "2513" ~ "Ortopedia - m\u00e3o",
          "2514" ~ "Ortopedia - quadril",
          "2515" ~ "Ortopedia - joelho",
          "2516" ~ "Ortopedia - tumor \u00f3sseo",
          "2517" ~ "Outros segmentos \u00f3sseos",
          "2601" ~ "UTI II adulto",
          "2602" ~ "UTI II neonatal",
          "2603" ~ "UTI II pedi\u00e1trica",
          "2604" ~ "UTI III adulto",
          "2605" ~ "UTI III neonatal",
          "2606" ~ "UTI III pedi\u00e1trica",
          "2607" ~ "UTI queimados",
          "2699" ~ "UTI I",
          "2701" ~ "Hospital tipo I em urg\u00eancia",
          "2702" ~ "Hospital tipo II em urg\u00eancia",
          "2703" ~ "Hospital tipo III em urg\u00eancia",
          "0901" ~ "Cuidados prolongados enferm cardiovasculares",
          "0902" ~ "Cuidados prolongados enferm pneumol\u00f3gicas",
          "0903" ~ "Cuidados prolongados enferm neurol\u00f3gicas",
          "0904" ~ "Cuidados prolongados enferm osteomusc/tec conjunt.",
          "0905" ~ "Cuidados prolongados enferm oncol\u00f3gicas",
          "0906" ~ "Cuidados prolongados enferm decorrentes AIDS",
          "0907" ~ "Cuidados prolongados enferm devido causas externas",
          "1301" ~ "Interna\u00e7\u00e3o domiciliar",
          "1901" ~ "Laqueadura",
          "1902" ~ "Vasectomia",
          "2801" ~ "Cuidados intermedi\u00e1rios neonatal",
          "2901" ~ "Videocirurgias",
          .default = Cod_Habilitacao
        )
      )
  }

  return(data)
}
