
#' Adiciona rotulos descritivos a partir de colunas de codigos
#'
#' @description Cria colunas de rotulos associada a colunas de codigos.
#'
#' @param dados DataFrame.
#' @param type_data String. O tipo da base de dados do CNES que sera baixado. Valores aceitos ("cnes", "leitos", "equipamentos", "habilitacao").
#'
#' @return O DataFrame recebido e as novas colunas.
#'
#' @examples
#' \dontrun{
#'   dados = labels(dados, "cnes")
#' }
#'
#' @export
labels = function(dados, type_data){
  `%>%` <- dplyr::`%>%`

  #> Leito---------------
  labels_tipo_leito <- c(
    "1" = "Cir\u00fargico",
    "2" = "Cl\u00ednico",
    "3" = "Complementar",
    "4" = "Obst\u00e9trico",
    "5" = "Pedi\u00e1trico",
    "6" = "Outras Especialidades",
    "7" = "Hospital/DIA"
  )
  labels_especialidade_leito <- c(
    "01" = "BUCO MAXILO FACIAL",
    "02" = "CARDIOLOGIA",
    "03" = "CIRURGIA GERAL",
    "04" = "ENDOCRINOLOGIA",
    "05" = "GASTROENTEROLOGIA",
    "06" = "GINECOLOGIA",
    "07" = "CIRURGICO/DIAGNOSTICO/TERAPEUTICO",
    "08" = "NEFROLOGIAUROLOGIA",
    "09" = "NEUROCIRURGIA",
    "10" = "OBSTETRICIA CIRURGICA",
    "11" = "OFTALMOLOGIA",
    "12" = "ONCOLOGIA",
    "13" = "ORTOPEDIATRAUMATOLOGIA",
    "14" = "OTORRINOLARINGOLOGIA",
    "15" = "PLASTICA",
    "16" = "TORAXICA",
    "31" = "AIDS",
    "32" = "CARDIOLOGIA",
    "33" = "CLINICA GERAL",
    "34" = "CRONICOS",
    "35" = "DERMATOLOGIA",
    "36" = "GERIATRIA",
    "37" = "HANSENOLOGIA",
    "38" = "HEMATOLOGIA",
    "39" = "LEITO/DIA",
    "40" = "NEFROUROLOGIA",
    "41" = "NEONATOLOGIA",
    "42" = "NEUROLOGIA",
    "43" = "OBSTETRICIA CLINICA",
    "44" = "ONCOLOGIA",
    "45" = "PEDIATRIA CLINICA",
    "46" = "PNEUMOLOGIA",
    "47" = "PSIQUIATRIA",
    "48" = "REABILITACAO",
    "49" = "PNEUMOLOGIA SANITARIA",
    "61" = "UTI ADULTO",
    "62" = "UTI INFANTIL",
    "63" = "UTI NEONATAL",
    "64" = "UNIDADE INTERMEDIARIA",
    "65" = "UNIDADE INTERMEDIARIA NEONATAL",
    "66" = "UNIDADE ISOLAMENTO",
    "67" = "TRANSPLANTE",
    "68" = "PEDIATRIA CIRURGICA",
    "69" = "AIDS",
    "70" = "FIBROSE CISTICA",
    "71" = "INTERCORRENCIA POS-TRANSPLANTE",
    "72" = "GERIATRIA",
    "73" = "SAUDE MENTAL",
    "74" = "UTI ADULTO - TIPO I",
    "75" = "UTI ADULTO - TIPO II",
    "76" = "UTI ADULTO - TIPO III",
    "77" = "UTI PEDIATRICA - TIPO I",
    "78" = "UTI PEDIATRICA - TIPO II",
    "79" = "UTI PEDIATRICA - TIPO III",
    "80" = "UTI NEONATAL - TIPO I",
    "81" = "UTI NEONATAL - TIPO II",
    "82" = "UTI NEONATAL - TIPO III",
    "83" = "UTI DE QUEIMADOS",
    "84" = "ACOLHIMENTO NOTURNO",
    "85" = "UTI CORONARIANA TIPO II - UCO TIPO II",
    "86" = "UTI CORONARIANA TIPO III - UCO TIPO III",
    "87" = "SAUDE MENTAL",
    "88" = "QUEIMADO ADULTO",
    "89" = "QUEIMADO PEDIATRICO",
    "90" = "QUEIMADO ADULTO",
    "91" = "QUEIMADO PEDIATRICO",
    "92" = "UNIDADE DE CUIDADOS INTERMED NEONATAL CONVENCIONAL",
    "93" = "UNIDADE DE CUIDADOS INTERMED NEONATAL CANGURU",
    "94" = "UNIDADE DE CUIDADOS INTERMEDIARIOS PEDIATRICO",
    "95" = "UNIDADE DE CUIDADOS INTERMED  ADULTO"
  )
  #> CNES---------------
  labels_cnes <- c(
    "0000396" = "HC da Univ. Federal de Pernambuco (HC-UFPE)",
    "0002534" = "HU da Universidade Federal de Sergipe (HU-UFS)",
    "0003816" = "HU Professor Edgard Santos (Hupes-UFBA)",
    "0004731" = "Maternidade Clim\u00e9rio de Oliveira (MCO-UFBA)",
    "0009709" = "HU Maria Aparecida Pedrossian (Humap-UFMS)",
    "0010510" = "HU da Universidade de Bras\u00edlia (HUB-UnB)",
    "0012505" = "HU Ant\u00f4nio Pedro (HUAP-UFF)",
    "0027049" = "HC da Univ. Federal de Minas Gerais (HC-UFMG)",
    "2006197" = "HU Professor Alberto Antunes (HUPAA-UFAL)",
    "2017644" = "HU Get\u00falio Vargas (HUGV-UFAM)",
    "2146339" = "Ambulat\u00f3rio Am\u00e9lio Marques (AAM-HC-UFU)",
    "2146355" = "Hospital de Cl\u00ednicas de Uberl\u00e2ndia (HC-UFU)",
    "2146371" = "Unidade Di\u00e1lise Hemodi\u00e1lise (UDH-HC-UFU)",
    "2206595" = "HC da Univ. Feder. do Tri\u00e2ngulo Mineiro (HC-UFTM)",
    "2218798" = "HU da Univ. Federal de Juiz de Fora (HU-UFJF)",
    "2244306" = "HU da Univ. Federal de Santa Maria (HUSM-UFSM)",
    "2252694" = "HE da Univ. Federal de Pelotas (HE-UFPel)",
    "2295415" = "HU Gaffree e Guinle (HUGG-Unirio)",
    "2332981" = "HU Jo\u00e3o de Barros Barreto (HUJBB-UFPA)",
    "2338424" = "HC da Universidade Federal de Goi\u00e1s (HC-UFG)",
    "2384299" = "Complexo do HC da Univ.Fed. do Paran\u00e1 (CHC-UFPR)",
    "2400243" = "HU Lauro Wanderley (HULW-UFPB)",
    "2409208" = "Maternidade Escola Janu\u00e1rio Cicco (Mejc-UFRN)",
    "2481286" = "Maternidade Escola Assis Chateaubriand (Meac-UFC)",
    "2504502" = "HU J\u00falio Maria Bandeira de Mello (HUJB-UFCG)",
    "2561492" = "HU Walter Cant\u00eddio (HUWC-UFC)",
    "2640244" = "Maternidade Victor F. do Amaral (MVFA-UFPR)",
    "2653982" = "Hospital Universit\u00e1rio Onofre Lopes (Huol-UFRN)",
    "2655411" = "Hospital Universit\u00e1rio J\u00falio Muller (HUJM-UFMT)",
    "2676060" = "Hospital Universit\u00e1rio Alcides Carneiro (HUAC-UFCG)",
    "2694751" = "HU Bettina Ferro de Souza (HUBFS-UFPA)",
    "2707675" = "HU Dr. Miguel Riet Correa Junior (HU-Furg)",
    "2710935" = "HU da Univ. Federal da Grande Dourados (HU-UFGD)",
    "2726653" = "HU da Universidade Federal do Maranh\u00e3o (HU-UFMA)",
    "3157245" = "HU da Univ. Federal de Santa Catarina (HU-UFSC)",
    "3285391" = "HU da Universidade Federal do Piau\u00ed (HU-UFPI)",
    "3432076" = "HU da Universidade Federal do Amap\u00e1 (HU-Unifap)",
    "3654826" = "Hospital de Doen\u00e7as Tropicais (HDT-UFT)",
    "4014111" = "Hospital Universit\u00e1rio Ana Bezerra (Huab-UFRN)",
    "4044916" = "HU Cassiano Ant\u00f4nio Moraes (Hucam-UFES)",
    "5586348" = "HU da Univ. Federal de S\u00e3o Carlos (HU-Ufscar)",
    "6042414" = "HU da Univ. Fed. Vale do S\u00e3o Francisco (HU-Univasf)",
    "6568343" = "Hospital Universit\u00e1rio de Lagarto (HUL-UFS)"
  )

  labels_sicla_cnes = c(
    "0000396"	= "HC-UFPE",
    "0002534"	= "HU-UFS",
    "0003816"	= "Hupes-UFBA",
    "0004731"	= "MCO-UFBA",
    "0009709"	= "Humap-UFMS",
    "0010510"	= "HUB-UnB",
    "0012505"	= "HUAP-UFF",
    "0027049"	= "HC-UFMG",
    "2006197"	= "HUPAA-UFAL",
    "2017644"	= "HUGV-UFAM",
    "2146339"	= "AAM-HC-UFU",
    "2146355"	= "HC-UFU",
    "2146371"	= "UDH-HC-UFU",
    "2206595"	= "HC-UFTM",
    "2218798"	= "HU-UFJF",
    "2244306"	= "HUSM-UFSM",
    "2252694"	= "HE-UFPel",
    "2295415"	= "HUGG-Unirio",
    "2332981"	= "HUJBB-UFPA",
    "2338424"	= "HC-UFG",
    "2384299"	= "CHC-UFPR",
    "2400243"	= "HULW-UFPB",
    "2409208"	= "Mejc-UFRN",
    "2481286"	= "Meac-UFC",
    "2504502"	= "HUJB-UFCG",
    "2561492"	= "HUWC-UFC",
    "2640244"	= "MVFA-UFPR",
    "2653982"	= "Huol-UFRN",
    "2655411"	= "HUJM-UFMT",
    "2676060"	= "HUAC-UFCG",
    "2694751"	= "HUBFS-UFPA",
    "2707675"	= "HU-Furg",
    "2710935"	= "HU-UFGD",
    "2726653"	= "HU-UFMA",
    "3157245"	= "HU-UFSC",
    "3285391"	= "HU-UFPI",
    "3432076"	= "HU-Unifap",
    "3654826"	= "HDT-UFT",
    "4014111"	= "Huab-UFRN",
    "4044916"	= "Hucam-UFES",
    "5586348"	= "HU-Ufscar",
    "6042414"	= "HU-Univasf",
    "6568343"	= "HU-UFS"
  )
  #> Equipamentos---------------
  labels_tipo_equipamento <- c(
    "1" = "Eq. De Diagnostico Por Imagem",
    "2" = "Eq. De Infra-Estrutura",
    "3" = "Eq. Por M\u00e9todos \u00d3pticos",
    "4" = "Eq. Por M\u00e9todos Gr\u00e1ficos",
    "5" = "Eq. Para Manuten\u00e7\u00e3o Da Vida",
    "6" = "Outros Eq.",
    "7" = "Eq. De Odontologia",
    "8" = "Eq. De Audiologia",
    "9" = "Eq. De Telessa\u00fade"
  )
  labels_equipamento <- c(
    "01" = "Gama C\u00e2mara",
    "02" = "Mam\u00f3grafo com Comando Simples",
    "03" = "Mam\u00f3grafo com Estereotaxia",
    "04" = "Raio X At\u00e9 100 Ma",
    "05" = "Raio X de 100 A 500 Ma",
    "06" = "Raio X Mais de 500ma",
    "07" = "Raio X Dent\u00e1rio",
    "08" = "Raio X com Fluoroscopia",
    "09" = "Raio X para Densitometria \u00d3ssea",
    "10" = "Raio X para Hemodin\u00e2mica",
    "11" = "Tom\u00f3grafo Computadorizado",
    "12" = "Resson\u00e2ncia Magn\u00e9tica",
    "13" = "Ultrassom Doppler Colorido",
    "14" = "Ultrassom Ec\u00f3grafo",
    "15" = "Ultrassom Convencional",
    "16" = "Processadora de Filme Exclusiva Para Mamografia",
    "17" = "Mam\u00f3grafo Computadorizado",
    "18" = "PET/CT",
    "19" = "Ar Condicionado",
    "20" = "Camera Frigorifica",
    "21" = "Controle Ambiental/Ar-condicionado Central",
    "22" = "Grupo Gerador",
    "23" = "Usina de Oxig\u00eanio",
    "24" = "Camara para Conserva\u00e7\u00e3o de Hemoderivados/Imuno/Termolabeis",
    "25" = "Camara para Conserva\u00e7\u00e3o de Imunobiologicos",
    "26" = "Condensador",
    "27" = "Freezer Cient\u00edfico",
    "28" = "Grupo Gerador (101 A 300 KVA)",
    "29" = "Grupo Gerador (8 A 100 KVA)",
    "30" = "Grupo Gerador (Acima de 300 KVA)",
    "31" = "Endosc\u00f3pio das Vias Respirat\u00f3rias",
    "32" = "Endosc\u00f3pio das Vias Urinarias",
    "33" = "Endosc\u00f3pio Digestivo",
    "34" = "Equipamentos para Optometria",
    "35" = "Laparosc\u00f3pico/V\u00eddeo",
    "36" = "Microsc\u00f3pio Cir\u00fargico",
    "37" = "Cadeira Oftalmol\u00f3gica",
    "38" = "Coluna Oftalmol\u00f3gica",
    "39" = "Refrator",
    "40" = "Lensometro",
    "41" = "Eletrocardi\u00f3grafo",
    "42" = "Eletroencefal\u00f3grafo",
    "43" = "Grupo Gerador de 1.500 (m\u00ednimo)",
    "44" = "Projetor ou Tabela de Optotipos",
    "45" = "Retinosc\u00f3pio",
    "46" = "Oftalmosc\u00f3pio",
    "47" = "Ceratometro",
    "48" = "Ton\u00f4metro de Aplana\u00e7\u00e3o",
    "49" = "Biomicroscopio (L\u00e2mpada de Fenda)",
    "50" = "Campimetro",
    "51" = "Bomba/Bal\u00e3o Intra-a\u00f3rtico",
    "52" = "Bomba de Infus\u00e3o",
    "53" = "Ber\u00e7o Aquecido",
    "54" = "Bilirrubinometro",
    "55" = "Debit\u00f4metro",
    "56" = "Desfibrilador",
    "57" = "Equipamento de Fototerapia",
    "58" = "Incubadora",
    "59" = "Marca-passo Tempor\u00e1rio",
    "60" = "Monitor de ECG",
    "61" = "Monitor de Press\u00e3o Invasivo",
    "62" = "Monitor de Press\u00e3o N\u00e3o Invasivo",
    "63" = "Reanimador Pulmonar/Ambu",
    "64" = "Respirador/Ventilador",
    "65" = "Grupo Gerador Port\u00e1til (at\u00e9 7 KVA)",
    "66" = "Refrigerador",
    "67" = "Caminh\u00e3o Ba\u00fa Refrigerado",
    "68" = "Embarca\u00e7\u00e3o para Transporte com Motor Popa (at\u00e9 12 pessoas)",
    "69" = "Empilhadeira",
    "70" = "Ve\u00edculo Utilit\u00e1rio (Tipo Furg\u00e3o)",
    "71" = "Aparelho de Diatermia por Ultrassom/Ondas Curtas",
    "72" = "Aparelho de Eletroestimula\u00e7\u00e3o",
    "73" = "Bomba de Infus\u00e3o de Hemoderivados",
    "74" = "Equipamentos de Af\u00e9rese",
    "75" = "Equipamento de Circula\u00e7\u00e3o Extracorp\u00f3rea",
    "76" = "Equipamento Para Hemodi\u00e1lise",
    "77" = "Forno de Bier",
    "78" = "Ve\u00edculo Pick-up Cabine Dupla 4x4 (Diesel)",
    "79" = "Equipo Odontol\u00f3gico Completo",
    "80" = "Compressor Odontol\u00f3gico",
    "81" = "Fotopolimerizador",
    "82" = "Caneta de Alta Rota\u00e7\u00e3o",
    "83" = "Caneta de Baixa Rota\u00e7\u00e3o",
    "84" = "Amalgamador",
    "85" = "Aparelho de Profilaxia C/Jato de Bicarbonato",
    "86" = "Emiss\u00f5es Otoac\u00fasticas Evocadas Transientes",
    "87" = "Emiss\u00f5es Otoac\u00fasticas Evocadas por Produto de Distor\u00e7\u00e3o",
    "88" = "Potencial Evocado Auditivo de Tronco Encef\u00e1lico Autom\u00e1tico",
    "89" = "Pot Evocado Aud Tronco Encef de Curta, Media e Longa Lat\u00eancia",
    "90" = "Audi\u00f4metro de Um Canal",
    "91" = "Audi\u00f4metro de Dois Canais",
    "92" = "Imitanciometro",
    "93" = "Imitanciometro Multifrequencial",
    "94" = "Cabine Ac\u00fastica",
    "95" = "Sistema de Campo Livre",
    "96" = "Sistema Completo de Refor\u00e7o Visual (VRA)",
    "97" = "Ganho de Inser\u00e7\u00e3o",
    "98" = "Hi-Pro"
  )
  #> Habilitacao ---------------
  labels_cod_habilitacao <- c(
    "0" = NA,
    "0101" =	"CENTRO DE REFERENCIA EM ATENCAO A SAUDE DO IDOSO",
    "0201" =	"CENTRO DE REFERENCIA EM CIRURGIA BARIATRICA",
    "0202" =	"UNID.DE ASSIST. DE ALTA COMPLEXIDADE AO PACIENTE PORTADOR DE OBESIDADE GRAVE",
    "0203" =	"ASSISTENCIA DE ALTA COMPLEXIDADE AO INDIVIDUO COM OBESIDADE",
    "0301" =	"CENTROS/NUCLEOS PARA REALIZACAO DE IMPLANTE COCLEAR",
    "0302" =	"DIAGNOSTICO, TRATAMENTO E REABILITACAO AUDITIVA NA MEDIA COMPLEXIDADE.",
    "0303" =	"DIAGNOSTICO, TRATAMENTO E REABILITACAO AUDITIVA NA ALTA COMPLEXIDADE",
    "0305" =	"ATENCAO ESPECIALIZADA AS PESSOAS COM DEFICIENCIA AUDITIVA",
    "0401" =	"CENTRO DE TRATAMENTO DA MA FORMACAO LABIO PALATAL",
    "0402" =	"LABORATORIO REGIONAL DE PROTESE DENTARIA",
    "0403" =	"CENTRO DE ESPECIALIDADES ODONTOLOGICAS I",
    "0404" =	"CENTRO DE ESPECIALIDADES ODONTOLOGICAS II",
    "0405" =	"CEO III - CENTRO DE ESPECIALIDADES ODONTOLOGICAS",
    "0406" =	"SERVICO DE ESPECIALIDADES EM SAUDE BUCAL",
    "0501" =	"CENTRO DE REFERENCIA EM OFTALMOLOGIA - NIVEL I",
    "0502" =	"CENTRO DE REFERENCIA EM OFTALMOLOGIA - NIVEL II",
    "0503" =	"UNIDADE DE ATENCAO ESPECIALIZADA EM OFTALMOLOGIA",
    "0504" =	"CENTRO DE REFERENCIA EM OFTALMOLOGIA",
    "0505" =	"PROJETO OLHAR BRASIL",
    "0506" =	"TRATAMENTO DO GLAUCOMA COM MEDICAMENTOS NO AMBITO DA POLITICA NACIONAL DE ATENCAO OFTALMOLOGICA",
    "0508" =	"TRATAMENTO DO GLAUCOMA COM MEDICAMENTOS DO COMPONENTE ESPECIALIZADO DA ASSISTENCIA FARMACEUTICA (CEAF)",
    "0601" =	"CLASSE I",
    "0602" =	"CLASSE II",
    "0603" =	"CLASSE III",
    "0604" =	"CLASSE IV",
    "0605" =	"CLASSE V",
    "0606" =	"CLASSE VI",
    "0607" =	"CLASSE VII",
    "0608" =	"CLASSE VIII",
    "0609" =	"CLASSE IX",
    "0610" =	"CLASSE X",
    "0611" =	"CLASSE XI",
    "0612" =	"CLASSE XII",
    "0613" =	"CLASSE XIII",
    "0614" =	"CLASSE XIV",
    "0615" =	"PNASS MAIOR QUE 80%",
    "0616" =	"CAPS I",
    "0617" =	"CAPS II",
    "0618" =	"CAPS III",
    "0619" =	"CAPS ALCOOL E DROGAS",
    "0620" =	"CAPS INFANTIL",
    "0621" =	"SERVICO HOSPITALAR DE REFERENCIA PARA A ATENCAO INTEGRAL AOS USUARIOS DE ALCOOL E OUTRAS DROGAS",
    "0622" =	"CLASSE I- ESTABELECIMENTO COM NUMERO DE LEITOS  ENTRE 20 E 80 COM PONTUACAO NO PNASH - PROGRAMA NACIONAL DE AVALIACAO DOS SERVICOS HOSPITALARES-  ENTRE 81% E 100%",
    "0623" =	"CLASSE II ESTABELECIMENTO COM NUMERO DE LEITOS  ENTRE 20 E 80 COM  PONTUACAO NO PNASH ENTRE 61% E 80 % E NUMERO DE LEITOS ENTRE 81 E 120 COM PONTUACAO NO PNASH ENTRE 81% E 100%",
    "0624" =	"CLASSE III ESTABELECIMENTO COM NUMERO DE LEITOS  ENTRE 81 E 120 COM  PONTUACAO NO PNASH ENTRE 61% E 80 % E NUMERO DE LEITOS ENTRE 121 E 160 COM PONTUACAO NO PNASH ENTRE 81% E 100%",
    "0625" =	"CLASSE IV ESTABELECIMENTO COM NUMERO DE LEITOS  ENTRE 121 E 160 COM  PONTUACAO NO PNASH ENTRE 61% E 80 % E NUMERO DE LEITOS ENTRE 161 E 200 COM PONTUACAO NO PNASH ENTRE 81% E 100%",
    "0626" =	"CLASSE V ESTABELECIMENTO COM NUMERO DE LEITOS  ENTRE 161 E 200 COM  PONTUACAO NO PNASH ENTRE 61% E 80 % E NUMERO DE LEITOS ENTRE 201 E 240 COM PONTUACAO NO PNASH ENTRE 81% E 100%",
    "0627" =	"CLASSE VI ESTABELECIMENTO COM NUMERO DE LEITOS  ENTRE 201 E 240 COM  PONTUACAO NO PNASH ENTRE 61% E 80 % E NUMERO DE LEITOS ENTRE 241 E 400 COM PONTUACAO NO PNASH ENTRE 81% E 100%",
    "0628" =	"CLASSE VII ESTABELECIMENTO COM NUMERO DE LEITOS  ENTRE 241 E 400 COM  PONTUACAO NO PNASH ENTRE 61% E 80 % E NUMERO DE LEITOS ACIMA DE 400 COM PONTUACAO NO PNASH ENTRE 81% E 100%",
    "0629" =	"CLASSE VIII ESTABELECIMENTO COM NUMERO DE LEITOS  ACIMA DE 400 E PONTUACAO NO PNASH ENTRE 61% E 80%",
    "0630" =	"PSIQUIATRIA III",
    "0631" =	"NIVEL I - ESTABELECMENTO DE SAUDE COM no DE LEITOS DE PSIQUIATRIA ATE 160",
    "0632" =	"NIVEL II - ESTABELECIMENTO DE SAUDE COM no DE LEITOS DE PSIQUIATRIA ENTRE 161 A 240",
    "0633" =	"NIVEL III - ESTABELECIMENTO DE SAUDE COM no DE LEITOS DE PSIQUIATRIA ENTRE 241 a 400",
    "0634" =	"NIVEL IV - ESTABELECIMENTO DE SAUDE COM no DE LEITOS DE PSIQUIATRIA ACIMA de 400",
    "0635" =	"CAPS AD III",
    "0636" =	"SERVICOS HOSPITALARES DE REFERENCIA PARA ATENCAO A PESSOAS COM SOFRIMENTO OU TRANTORNO MENTAL INCLUINDO AQUELAS COM NECESSIDADES DECORRENTES DO USO DE ALCOOL E OUTRAS DROGAS",
    "0637" =	"CAPS AD IV",
    "0701" =	"SERVICO DE REFERENCIA DE SAUDE DO TRABALHADOR ESTADUAL A",
    "0702" =	"SERVICO DE REFERENCIA DE SAUDE DO TRABALHADOR ESTADUAL B",
    "0703" =	"SERVICO DE REFERENCIA DE SAUDE DO TRABALHADOR ESTADUAL C",
    "0704" =	"SERVICO DE REFERENCIA DE SAUDE DO TRABALHADOR REGIONAL A",
    "0705" =	"SERVICO DE REFERENCIA DE SAUDE DO TRABALHADOR REGIONAL B",
    "0706" =	"SERVICO DE REFERENCIA DE SAUDE DO TRABALHADOR REGIONAL C",
    "0801" =	"UNIDADE DE ASSISTENCIA DE ALTA COMPLEXIDADE CARDIOVASCULAR*",
    "0802" =	"CENTRO DE REFERENCIA EM ALTA COMPLEXIDADE CARDIOVASCULAR**",
    "0803" =	"CIRURGIA CARDIOVASCULAR E PROCEDIMENTOS EM CARDIOLOGIA INTERVENCIONISTA",
    "0804" =	"CIRURGIA CARDIOVASCULAR PEDIATRICA",
    "0805" =	"CIRURGIA VASCULAR",
    "0806" =	"CIRURGIA VASCULAR E PROCEDIMENTOS ENDOVASCULARES EXTRACARDIACOS",
    "0807" =	"LABORATORIO DE ELETROFISIOLOGIA, CIRURGIA CARDIOVASCULAR E PROCEDIMENTOS DE CARDIOLOGIA INTERVENCIONISTA. O",
    "0808" =	"IMPLANTE DE MARCAPASSO DEFINITIVO",
    "0809" =	"CIRURGIA CARDIACA",
    "0810" =	"LAB. ELETROFISIOLOGICO E TERAPIA INTERVENCIONISTA",
    "0811" =	"QUALISUS CARDIO NIVEL A",
    "0812" =	"QUALISUS CARDIO NIVEL B",
    "0813" =	"QUALISUS CARDIO NIVEL C",
    "0814" =	"QUALISUS CARDIO NIVEL D",
    "0815" =	"IMPLANTE PERCUTANEO DE VALVULA AORTICA (TAVI)",
    "0901" =	"CUIDADOS PROLONGADOS - ENFERMIDADES CARDIOVASCULARES",
    "0902" =	"CUIDADOS PROLONGADOS - ENFERMIDADES PNEUMOLIGICAS",
    "0903" =	"CUIDADOS PROLONGADOS - ENFERMIDADES NEUROLOGICAS",
    "0904" =	"CUIDADOS PROLONGADOS - ENFERMIDADES OSTEOMUSCULAR E DO TECIDO CONJUNTIVO",
    "0905" =	"ENFERMIDADES ONCOLOGICAS",
    "0906" =	"CUIDADOS PROLONGADOS - ENFERMIDADES DECORRENTES DA AIDS",
    "0907" =	"CUIDADOS PROLONGADOS - ENFERMIDADES DEVIDO A CAUSAS EXTERNAS",
    "0908" =	"UNIDADE DE INTERNACAO EM CUIDADOS PROLONGADOS(UCP)",
    "0909" =	"HOSPITAL ESPECIALIZADO EM CUIDADOS PROLONGADOS (HCP)",
    "1001" =	"CENTRO DE REFERENCIA NO TRATAMENTO DA DOR CRONICA",
    "1101" =	"SERVICO HOSPITALAR PARA TRATAMENTO AIDS",
    "1102" =	"LABORATORIO ESPECIALIZADO EM CONTAGEM DE LINFOCITOS T CD4+/CD8+ e HIV-1 QUANTIFICACAO do RNA",
    "1103" =	"TRATAMENTO DA LIPOATROFIA FACIAL DO PORTADOR DE HIV/AIDS",
    "1104" =	"TRATAMENTO DA LIPODISTROFIA DO PORTADOR DE HIV/AIDS",
    "1105" =	"LABORATORIO ESPECIALIZADO EM CONTAGEM DE LINFOCITOS T CD4+/CD8+",
    "1106" =	"LABORATORIO ESPECIALIZADO EM QUANTIFICACAO do RNA do HIV-1",
    "1201" =	"FIBROSE CISTICA - HOSPITAL DIA",
    "1202" =	"PROCEDIMENTOS CIRURGICOS, DIAGNOSTICOS OU TERAPEUTICOS -HOSPITAL DIA",
    "1203" =	"HOSPITAL DIA - AIDS",
    "1204" =	"HOSPITAL DIA EM INTERCORRENCIAS POS - TRANSPLANTE DE MEDULA OSSEA E DE OUTROS PRECURSORES HEMATOPOETICOS",
    "1205" =	"HOSPITAL DIA - GERIATRIA",
    "1206" =	"HOSPITAL DIA - SAUDE MENTAL",
    "1301" =	"INTERNACAO DOMICILIAR",
    "1302" =	"SERVICO DE ATENCAO DOMICILIAR",
    "1401" =	"REFERENCIA HOSPITALAR EM ATENDIMENTO SECUNDARIO A GESTACAO DE ALTO RISCO",
    "1402" =	"REFERENCIA HOSPITALAR EM ATENDIMENTO TERCIARIO A GESTACAO DE ALTO RISCO",
    "1403" =	"UNIDADE QUE REALIZA ASSISTENCIA AO PARTO SEM DISTOCIA POR ENFERMEIRO(A) OBSTETRA",
    "1404" =	"HOSPITAL AMIGO DA CRIANCA",
    "1405" =	"CENTRO DE REFERENCIA EM TRIAGEM NEONATAL /ACOMPANHAMENTO E TRATAMENTO DE DOENCAS CONGENITAS - FENILCETONURIA/HIPOTIREOIDISMO CONGENITO",
    "1406" =	"CENTRO DE REFERENCIA EM TRIAGEM NEONATAL /ACOMPANHAMENTO E TRATAMENTO - DOENCAS FALCIFORMES E OUTRAS HEMOGLOBINOPATIAS",
    "1407" =	"CENTRO DE REFERENCIA EM TRIAGEM NEONATAL/ACOMPANHAMENTO E TRATAMENTO - FIBROSE CISTICA",
    "1408" =	"REFERENCIA EM TRIAGEM NEONATAL ETAPA I",
    "1409" =	"SERVICO DIAGNOSTICO DE FIBROSE CISTICA",
    "1410" =	"UNIDADE DE CENTRO DE PARTO NORMAL INTRA-HOSPITALAR TIPO I 3 PPP (CPNI I 3 PPP)",
    "1411" =	"UNIDADE DE CENTRO DE PARTO NORMAL INTRA-HOSPITALAR TIPO I 5 PPP (CPNI I 5 PPP)",
    "1412" =	"UNIDADE DE CENTRO DE PARTO NORMAL PERI-HOSPITALAR 5PPP",
    "1413" =	"ATENCAO HOSPITALAR DE REFERENCIA A GESTACAO DE ALTO RISCO TIPO I (GAR I)",
    "1414" =	"ATENCAO HOSPITALAR DE REFERENCIA A GESTACAO DE ALTO RISCO TIPO II (GAR II)",
    "1415" =	"CASA DA GESTANTE, BEBE E PUERPERA",
    "1416" =	"HOSPITAL AMIGO DA CRIANCA",
    "1417" =	"UNIDADE DE CENTRO DE PARTO NORMAL PERI-HOSPITALAR 3PPP",
    "1418" =	"UNIDADE DE CENTRO DE PARTO NORMAL INTRA-HOSPITALAR TIPO II 3 PPP (CPNI II 3 PPP)",
    "1419" =	"UNIDADE DE CENTRO DE PARTO NORMAL INTRA-HOSPITALAR TIPO II 5 PPP (CPNI II 5 PPP)",
    "1501" =	"UNIDADE DE ASSISTENCIA DE ALTA COMPLEXIDADE EM NEFROLOGIA(SERVICO DE NEFROLOGIA)",
    "1502" =	"CENTRO DE REFERENCIA DE ALTA COMPLEXIDADE EM NEFROLOGIA",
    "1503" =	"HEMODIALISE II",
    "1504" =	"ATENCAO ESPECIALIZADA EM DRC COM HEMODIALISE",
    "1505" =	"ATENCAO ESPECIALIZADA EM DRC COM DIALISE PERITONEAL",
    "1506" =	"ATENCAO ESPECIALIZADA EM DRC NOS ESTAGIOS 4 E 5 (PRE-DIALITICO)",
    "1507" =	"UNIDADE ESPECIALIZADA EM DRC COM TRS/DIALISE TIPO I COM HEMODIALISE",
    "1508" =	"UNIDADE ESPECIALIZADA EM DRC COM TRS/DIALISE TIPO I COM DIALISE PERITONEAL",
    "1509" =	"UNIDADE ESPECIALIZADA EM DRC COM TRS/DIALISE TIPO II COM HEMODIALISE",
    "1510" =	"UNIDADE ESPECIALIZADA EM DRC COM TRS/DIALISE TIPO II COM DIALISE PERITONEAL",
    "1511" =	"UNIDADE ESPECIALIZADA EM DRC COM TRS/DIALISE TIPO III COM HEMODIALISE",
    "1512" =	"UNIDADE ESPECIALIZADA EM DRC COM TRS/DIALISE TIPO III COM DIALISE PERITONEAL",
    "1513" =	"UNIDADE ESPECIALIZADA EM DRC COM TRS/DIALISE TIPO IV COM HEMODIALISE",
    "1514" =	"UNIDADE ESPECIALIZADA EM DRC COM TRS/DIALISE TIPO IV COM DIALISE PERITONEAL",
    "1601" =	"UNIDADE DE ASSISTENCIA DE ALTA COMPLEXIDADE EM NEUROLOGIA/NEUROCIRURGIA*.",
    "1602" =	"CENTRO DE REFERENCIA DE ALTA COMPLEXIDADE EM NEUROLOGIA/NEUROCIRURGIA**.",
    "1603" =	"TRAUMA E ANOMALIAS DO DESENVOLVIMENTO",
    "1604" =	"COLUNA E DOS NERVOS PERIFERICOS",
    "1605" =	"TUMORES DO SISTEMA NERVOSO",
    "1606" =	"NEUROCIRURGIA VASCULAR",
    "1607" =	"TRATAMENTO NEUROCIRURGICO DA DOR E FUNCIONAL",
    "1608" =	"INVESTIGACAO E CIRURGIA DE EPILEPSIA",
    "1609" =	"TRATAMENTO NEURO ENDOVASCULAR",
    "1610" =	"NEUROCIRURGIA FUNCIONAL ESTERIOTAXICA",
    "1611" =	"EPILEPSIA",
    "1612" =	"NEUROCIRURGIA I",
    "1613" =	"NEUROCIRURGIA II",
    "1614" =	"NEUROCIRURGIA III",
    "1615" =	"CENTRO DE ATENDIMENTO DE URGENCIA TIPO I AOS PACIENTES COM AVC",
    "1616" =	"CENTRO DE ATENDIMENTO DE URGENCIA TIPO II AOS PACIENTES COM AVC",
    "1617" =	"CENTRO DE ATENDIMENTO DE URGENCIA TIPO III AOS PACIENTES COM AVC",
    "1618" =	"NEUROCIRURGIA ENDOVASCULAR/TROMBECTOMIA MECANICA",
    "1701" =	"CENTRO DE ALTA COMPLEXIDADE EM ONCOLOGIA - CACON I",
    "1702" =	"CENTRO DE ALTA COMPLEXIDADE EM ONCOLOGIA - CACON II",
    "1703" =	"CENTRO DE ALTA COMPLEXIDADE EM ONCOLOGIA - CACON III",
    "1704" =	"SERVICO ISOLADO DE RADIOTERAPIA",
    "1705" =	"SERVICO ISOLADO DE QUIMIOTERAPIA",
    "1706" =	"UNACON",
    "1707" =	"UNACON COM SERVICO DE RADIOTERAPIA",
    "1708" =	"UNACON COM SERVICO DE HEMATOLOGIA",
    "1709" =	"UNACON COM SERVICO DE ONCOLOGIA PEDIATRICA",
    "1710" =	"UNACON EXCLUSIVA DE HEMATOLOGIA",
    "1711" =	"UNACON EXCLUSIVA DE ONCOLOGIA PEDIATRICA",
    "1712" =	"CACON",
    "1713" =	"CACON COM SERVICO DE ONCOLOGIA PEDIATRICA",
    "1714" =	"HOSPITAL GERAL COM CIRURGIA ONCOLOGICA",
    "1715" =	"SERVICO DE RADIOTERAPIA DE COMPLEXO HOSPITALAR",
    "1716" =	"SERVICO DE ONCOLOGIA CLINICA DE COMPLEXO HOSPITALAR",
    "1717" =	"ONCOLOGIA CIRURGICA HOSPITAL PORTE A",
    "1718" =	"ONCOLOGIA CIRURGICA HOSPITAL PORTE B",
    "1719" =	"SERVICO DE REFERENCIA PARA DIAGNOSTICO E TRATAMENTO DE LESOES PRECURSORAS DO CANCER DO COLO DE UTERO SRC",
    "1720" =	"SERVICO DE REFERENCIA PARA DIAGNOSTICO DE CANCER DE MAMA SDM",
    "1721" =	"HOSPITAL GERAL COM CIRURGIA DE CANCER DE COMPLEXO HOSPITALAR",
    "1722" =	"TRATAMENTOS INTEGRADOS SINCRONICOS EM ONCOLOGIA",
    "1723" =	"RECONSTRUCAO MAMARIA POS-MASTECTOMIA TOTAL",
    "1801" =	"CENTRO DE REFERENCIA DE TRATAMENTO DE OSTEOGENESIS IMPERFECTA",
    "1901" =	"LAQUEADURA",
    "1902" =	"VASECTOMIA",
    "2001" =	"PROGRAMA DE ASSISTENCIA VENTILADORA NAO INVASIVA AOS PORTADORES DE DOENCAS NEUROMUSCULARES",
    "2101" =	"CENTRO DE REFERENCIA EM ASSISTENCIA A QUEIMADOS - MEDIA COMPLEXIDADE",
    "2102" =	"CENTRO DE REFERENCIA EM ASSISTENCIA A QUEIMADOS - ALTA COMPLEXIDADE",
    "2201" =	"CENTRO DE REFERENCIA DE REABILITACAO EM MEDICINA FISICA",
    "2202" =	"SERVICO DE REABILITACAO FISICA - NIVEL INTERMEDIARIO",
    "2203" =	"UNIDADE DE REABILITACAO VISUAL",
    "2204" =	"CENTRO DE REABILITACAO AUDITIVA NA MEDIA COMPLEXIDADE",
    "2205" =	"CENTRO DE REABILITACAO AUDITIVA NA ALTA COMPLEXIDADE",
    "2206" =	"CENTRO DE REABILITACAO INTELECTUAL",
    "2207" =	"NUCLEO DE ATENCAO A CRIANCA E ADOLESCENTE COM TRANSTORNO DO ESPECTRO AUTISTA",
    "2208" =	"CENTRO ESPECIALIZADO EM REABILITACAO (CER) - MODALIDADE FISICA",
    "2209" =	"CENTRO ESPECIALIZADO EM REABILITACAO (CER) - MODALIDADE INTELECTUAL",
    "2210" =	"CENTRO ESPECIALIZADO EM REABILITACAO (CER) - MODALIDADE AUDITIVA",
    "2211" =	"CENTRO ESPECIALIZADO EM REABILITACAO (CER) - MODALIDADE VISUAL",
    "2212" =	"OFICINA ORTOPEDICA FIXA",
    "2213" =	"OFICINA ORTOPEDICA ITINERANTE",
    "2301" =	"UNIDADE DE ASSISTENCIA DE ALTA COMPLEXIDADE EM TERAPIA NUTRICIONAL*",
    "2302" =	"CENTRO DE REFERENCIA DE ALTA COMPLEXIDADE EM TERAPIA NUTRICIONAL",
    "2303" =	"ENTERAL",
    "2304" =	"ENTERAL E PARENTERAL",
    "2305" =	"ENTERAL E PARENTERAL COM MANIPULACAO E FABRICACAO DA FORMULA NUTRICIONAL",
    "2306" =	"NUTRICAO ENTERAL",
    "2401" =	"TRANSPLANTE DE MEDULA OSSEA - AUTOGENICO",
    "2402" =	"TRANSPLANTE DE MEDULA OSSEA - ALOGENICO APARENTADO",
    "2403" =	"TRANSPLANTE DE MEDULA OSSEA - ALOGENICO NAO APARENTADO",
    "2404" =	"TRANSPLANTE DE PANCREAS",
    "2405" =	"CONJUGADO RIM E PANCREAS",
    "2407" =	"TRANSPLANTE DE CORNEA/ESCLERA",
    "2408" =	"TRANSPLANTE DE RIM",
    "2409" =	"TRANSPLANTE DE FIGADO",
    "2410" =	"TRANSPLANTE DE PULMAO",
    "2411" =	"TRANSPLANTE DE CORACAO",
    "2412" =	"BUSCA ATIVA DE ORGAOS",
    "2413" =	"BANCO DE TECIDO OCULAR HUMANO",
    "2414" =	"BANCO DE VALVULAS CARDIACAS",
    "2415" =	"BANCO DE TECIDO MUSCULO ESQUELETICO",
    "2416" =	"BANCO DE SANGUE E CORDAO UMBILICAL E PLACENTARIO",
    "2417" =	"EXAMES DE HISTOCOMPATIBILIDADE ATRAVES DE SOROLOGIA - TIPO I",
    "2418" =	"EXAMES DE HISTOCOMPATIBILIDADE ATRAVES DE SOROLOGIA E OU BIOLOGIA MOLECULAR - TIPO II",
    "2419" =	"BANCO DE PELE HUMANA",
    "2420" =	"RETIRADA DE ORGAOS E TECIDOS",
    "2421" =	"BANCO DE MULTITECIDOS",
    "2422" =	"TRANSPLANTE DE TECIDO MUSCULO ESQUELETICO",
    "2423" =	"TRANSPLANTE DA VALVULA CARDIACA HUMANA",
    "2424" =	"TRANSPLANTE DE PELE",
    "2425" =	"CADASTRAMENTO DE DOADORES VOLUNTARIOS DE MEDULA OSSEA E OUTROS PRECURSORES HEMATOPOETICOS",
    "2426" =	"ESTABELECIMENTO DE SAUDE DE NIVEL A",
    "2427" =	"ESTABELECIMENTO DE SAUDE DE NIVEL B",
    "2428" =	"ESTABELECIMENTO DE SAUDE DE NIVEL C",
    "2429" =	"ESTABELECIMENTO DE SAUDE DE NIVEL D",
    "2430" =	"TRANSPLANTE DE FIGADO POR IHH FEBRE AMARELA",
    "2431" =	"QUALIDOT NIVEL A",
    "2432" =	"QUALIDOT NIVEL B",
    "2433" =	"QUALIDOT NIVEL C",
    "2434" =	"QUALIDOT NIVEL D",
    "2435" =	"QUALIDOT NIVEL E",
    "2436" =	"INCREMENTO FINANCEIRO SNT TMO NIVEL A",
    "2437" =	"INCREMENTO FINANCEIRO SNT TMO NIVEL B",
    "2438" =	"INCREMENTO FINANCEIRO SNT TMO NIVEL C",
    "2439" =	"INCREMENTO FINANCEIRO SNT TMO NIVEL D",
    "2440" =	"INCREMENTO FINANCEIRO SNT TMO NIVEL E",
    "2441" =	"INCREMENTO FINANCEIRO SNT PANCREAS NIVEL A",
    "2442" =	"INCREMENTO FINANCEIRO SNT PANCREAS NIVEL B",
    "2443" =	"INCREMENTO FINANCEIRO SNT PANCREAS NIVEL C",
    "2444" =	"INCREMENTO FINANCEIRO SNT PANCREAS NIVEL D",
    "2445" =	"INCREMENTO FINANCEIRO SNT PANCREAS NIVEL E",
    "2446" =	"INCREMENTO FINANCEIRO SNT RIM NIVEL A",
    "2447" =	"INCREMENTO FINANCEIRO SNT RIM NIVEL B",
    "2448" =	"INCREMENTO FINANCEIRO SNT RIM NIVEL C",
    "2449" =	"INCREMENTO FINANCEIRO SNT RIM NIVEL D",
    "2450" =	"INCREMENTO FINANCEIRO SNT RIM NIVEL E",
    "2451" =	"INCREMENTO FINANCEIRO SNT FIGADO NIVEL A",
    "2452" =	"INCREMENTO FINANCEIRO SNT FIGADO NIVEL B",
    "2453" =	"INCREMENTO FINANCEIRO SNT FIGADO NIVEL C",
    "2454" =	"INCREMENTO FINANCEIRO SNT FIGADO NIVEL D",
    "2455" =	"INCREMENTO FINANCEIRO SNT FIGADO NIVEL E",
    "2456" =	"INCREMENTO FINANCEIRO SNT PULMAO NIVEL A",
    "2457" =	"INCREMENTO FINANCEIRO SNT PULMAO NIVEL B",
    "2458" =	"INCREMENTO FINANCEIRO SNT PULMAO NIVEL C",
    "2459" =	"INCREMENTO FINANCEIRO SNT PULMAO NIVEL D",
    "2460" =	"INCREMENTO FINANCEIRO SNT PULMAO NIVEL E",
    "2461" =	"INCREMENTO FINANCEIRO SNT CORACAO NIVEL A",
    "2462" =	"INCREMENTO FINANCEIRO SNT CORACAO NIVEL B",
    "2463" =	"INCREMENTO FINANCEIRO SNT CORACAO NIVEL C",
    "2464" =	"INCREMENTO FINANCEIRO SNT CORACAO NIVEL D",
    "2465" =	"INCREMENTO FINANCEIRO SNT CORACAO NIVEL E",
    "2501" =	"UNIDADE DE ASSISTENCIA DE ALTA COMPLEXIDADE EM TRAUMATO-ORTOPEDIA*",
    "2502" =	"CENTRO DE REFERENCIA DE ALTA COMPLEXIDADE EM TRAUMATO-ORTOPEDIA**",
    "2503" =	"COLUNA",
    "2504" =	"CINTURA ESCAPULAR, OMBRO, BRACO E COTOVELO",
    "2505" =	"ANTEBRACO, PUNHO E MAO",
    "2506" =	"CINTURA PELVICA, QUADRIL, COXA",
    "2507" =	"COXA, JOELHO E PERNA",
    "2508" =	"PERNA, TORNOZELO E PE",
    "2509" =	"ORTOPEDIA INFANTIL",
    "2510" =	"TRAUMATOLOGIA ORTOPEDICA DE URGENCIA",
    "2511" =	"ORTOPEDIA - COLUNA",
    "2512" =	"ORTOPEDIA - OMBRO",
    "2513" =	"ORTOPEDIA - MAO",
    "2514" =	"ORTOPEDIA - QUADRIL",
    "2515" =	"ORTOPEDIA - JOELHO",
    "2516" =	"ORTOPEDIA - TUMOR OSSEO",
    "2517" =	"OUTROS SEGMENTOS OSSEOS",
    "2518" =	"ADESAO A ESTRATEGIA DE AUMENTO DO ACESSO AOS PROCEDIMENTOS-TOM",
    "2601" =	"UTI II ADULTO",
    "2602" =	"UTI II NEONATAL",
    "2603" =	"UTI II PEDIATRICA",
    "2604" =	"UTI III ADULTO",
    "2605" =	"UTI III NEONATAL",
    "2606" =	"UTI III PEDIATRICA",
    "2607" =	"UTI QUEIMADOS",
    "2608" =	"UTI CORONARIANA TIPO II",
    "2609" =	"UTI CORONARIANA TIPO III",
    "2610" =	"UNIDADE DE TERAPIA INTENSIVA NEONATAL TIPO II - UTIN II",
    "2611" =	"UNIDADE DE TERAPIA INTENSIVA NEONATAL TIPO III - UTIN III",
    "2612" =	"UTI II ADULTO - SINDROME RESPIRATORIA AGUDA GRAVE (SRAG) - COVID-19",
    "2613" =	"UTI II PEDIATRICA - SINDROME RESPIRATORIA AGUDA GRAVE (SRAG) - COVID-19",
    "2696" =	"UTI I ADULTO",
    "2697" =	"UTI I NEONATAL",
    "2698" =	"UTI I PEDIATRICA",
    "2699" =	"UTI I",
    "2701" =	"HOSPITAL TIPO I EM URGENCIA",
    "2702" =	"HOSPITAL TIPO II EM URGENCIA",
    "2703" =	"HOSPITAL TIPO III EM URGENCIA",
    "2704" =	"SAMU 192 - SUPORTE BASICO DE VIDA",
    "2705" =	"SAMU 192 - SUPORTE AVANCADO DE VIDA",
    "2706" =	"SAMU 192 - EQUIPE DE AEROMEDICO",
    "2707" =	"SAMU 192 - EQUIPE DE EMBARCACAO",
    "2708" =	"SAMU 192 - VEICULOS DE INTERVENCAO RAPIDA (VIR)",
    "2709" =	"SAMU 192 - MOTOLANCIA",
    "2710" =	"CENTRAL DE REGULACAO DAS URGENCIAS",
    "2711" =	"ADMINISTRACAO PRE-HOSPITALAR DE TENECTEPLASE",
    "2801" =	"CUIDADOS INTERMEDIARIOS",
    "2802" =	"UNIDADE DE CUIDADOS INTERMEDIARIOS NEONATAL CONVENCIONAL (UCINCO)",
    "2803" =	"UNIDADE DE CUIDADOS INTERMEDIARIOS NEONATAL CANGURU (UCINCA)",
    "2806" =	"LEITO COM SUPORTE VENTILATORIO PULMONAR - COVID-19",
    "2901" =	"VIDEOCIRURGIAS",
    "2902" =	"PROGRAMA NACIONAL DE REDUCAO DE FILAS DE CIRURGIAS ELETIVAS",
    "3001" =	"UNIDADE DE ATENCAO ESPECIALIZADA NO PROCESSO TRANSEXUALIZADOR",
    "3002" =	"ATENCAO ESPECIALIZADA NO PROCESSO TRANSEXUALIZADOR - MODALIDADE AMBULATORIAL",
    "3003" =	"ATENCAO ESPECIALIZADA NO PROCESSO TRANSEXUALIZADOR - MODALIDADE HOSPITALAR",
    "3101" =	"HPP- HOSPITAL DE PEQUENO PORTE",
    "3201" =	"UNIDADE DE MAMOGRAFIA MOVEL",
    "3202" =	"LABORATORIO DE EXAMES CITOPATOLOGICOS DO COLO DE UTERO - TIPO I",
    "3203" =	"LABORATORIO DE MONITORAMENTO EXTERNO DE QUALIDADE DE EXAMES CITOPATOLOGICOS DE COLO DE UTERO - TIPO II",
    "3301" =	"LABORATORIO DE REFERENCIA NACIONAL (LRN)",
    "3302" =	"LABORATORIO DE REFERENCIA REGIONAL (LRN)",
    "3303" =	"CENTRO COLABORADOR",
    "3304" =	"LABORATORIO DE FRONTEIRA (LF)",
    "3401" =	"CENTRO DE TRAUMA TIPO I",
    "3402" =	"CENTRO DE TRAUMA TIPO II",
    "3403" =	"CENTRO DE TRAUMA TIPO III",
    "3501" =	"ATENCAO ESPECIALIZADA EIXO I DR DE ORIGEM GENETICA: 1 ANOMALIAS CONGENITAS OU DE MANIFESTACAO TARDIA",
    "3502" =	"ATENCAO ESPECIALIZADA EIXO I DR DE ORIGEM GENETICA: 2 DEFICIENCIA INTELECTUAL",
    "3503" =	"ATENCAO ESPECIALIZADA EIXO I DR DE ORIGEM GENETICA: 3 ERRO INATO DO METABOLISMO (EIM)",
    "3504" =	"ATENCAO ESPECIALIZADA EIXO II DR DE ORIGEM NAO GENETICA: 1 DOENCAS RARAS INFLAMATORIAS",
    "3505" =	"ATENCAO ESPECIALIZADA EIXO II DR DE ORIGEM NAO GENETICA: 2 DOENCAS RARAS INFECCIOSAS",
    "3506" =	"ATENCAO ESPECIALIZADA EIXO II DR DE ORIGEM NAO GENETICA: 2 DOENCAS RARAS AUTOIMUNES",
    "3507" =	"SERVICO DE REFERENCIA EIXO I DR DE ORIGEM GENETICA: 1 ANOMALIAS CONGENITAS OU DE MANIFESTACAO TARDIA",
    "3508" =	"SERVICO DE REFERENCIA EIXO I DR DE ORIGEM GENETICA: 2 DEFICIENCIA INTELECTUAL",
    "3509" =	"SERVICO DE REFERENCIA EIXO I DR DE ORIGEM GENETICA: 3 ERRO INATO DO METABOLISMO (EIM)",
    "3510" =	"SERVICO DE REFERENCIA EIXO II DR DE ORIGEM NAO GENETICA 3-DOENCAS RARAS AUTOIMUNES",
    "3511" =	"SERVICO DE REFERENCIA EIXO II DR DE ORIGEM NAO GENETICA 2-DOENCAS RARAS INFLAMATORIAS",
    "3512" =	"SERVICO DE REFERENCIA EIXO II DR DE ORIGEM NAO GENETICA 1-DOENCAS RARAS INFECCIOSAS",
    "3513" =	"ATENCAO ESPECIALIZADA EM DOENCAS RARAS - EIXO II  DR DE ORIGEM NAO GENETICA: 4 OUTRAS DOENCAS RARAS DE ORIGEM NAO GENETICA",
    "3514" =	"SERVICO DE REFERENCIA EM DOENCAS RARAS - EIXO II DR DE ORIGEM NAO GENETICA: 4 OUTRAS DOENCA RARA DE ORIGEM NAO GENETICA",
    "3515" =	"SERVICO DE ACONSELHAMENTO GENETICO",
    "3601" =	"SITIO TESTADOR DE ACIDOS NUCLEICOS (SIT-NAT)",
    "3701" =	"COLETA DE VESTIGIOS DE VIOLENCIA SEXUAL",
    "3801" =	"PROGRAMA MAIS ACESSO A ESPECIALISTAS"
  )
  #> Procedimentos ---------------
  labels_grupos_procedimentos <- c(
   "1" = "1-A\u00e7\u00f5es de promo\u00e7\u00e3o e preven\u00e7\u00e3o em sa\u00fade",
   "2" = "2-Procedimentos com finalidade diagn\u00f3stica",
   "3" = "3-Procedimentos cl\u00ednicos",
   "4" = "4-Procedimentos cir\u00fargicos",
   "5" = "5-Transplantes de \u00f3rg\u00e3os, tecidos e c\u00e9lulas",
   "6" = "6-Medicamentos",
   "7" = "7-\u00d3rteses, pr\u00f3teses e materiais especiais",
   "8" = "8-A\u00e7\u00f5es complementares da aten\u00e7\u00e3o \u00e0 sa\u00fade",
   "9" = "9-Procedimentos para Oferta de Cuidados Integrados"
  )

  #> Motivo saida permanencia---------------
  labels_motivo_saida_permanencia <- c(
    "11" = "11-Alta curado",
    "12" = "12-Alta melhorado",
    "14" = "14-Alta a pedido",
    "15" = "15-Alta com previs\u00e3o de retorno p/acomp do paciente",
    "16" = "16-Alta por evas\u00e3o",
    "18" = "18-Alta por outros motivos",
    "19" = "19-Alta de paciente agudo em psiquiatria",
    "21" = "21-Perman\u00eancia por caracter\u00edsticas pr\u00f3prias da doen\u00e7a",
    "22" = "22-Perman\u00eancia por intercorr\u00eancia",
    "23" = "23-Perman\u00eancia por impossibilidade s\u00f3cio-familiar",
    "24" = "24-Perman\u00eancia proc doa\u00e7\u00e3o \u00f3rg, tec, c\u00e9l-doador vivo",
    "25" = "25-Perman\u00eancia proc doa\u00e7\u00e3o \u00f3rg, tec, c\u00e9l-doador morto",
    "26" = "26-Perman\u00eancia por mudan\u00e7a de procedimento",
    "27" = "27-Perman\u00eancia por reopera\u00e7\u00e3o",
    "28" = "28-Perman\u00eancia por outros motivos",
    "29" = "29-Transfer\u00eancia para interna\u00e7\u00e3o domiciliar",
    "32" = "32-Transfer\u00eancia para interna\u00e7\u00e3o domiciliar",
    "31" = "31-Transfer\u00eancia para outro estabelecimento",
    "41" = "41-\u00d3bito com DO fornecida pelo m\u00e9dico assistente",
    "42" = "42-\u00d3bito com DO fornecida pelo IML",
    "43" = "43-\u00d3bito com DO fornecida pelo SVO",
    "51" = "51-Encerramento administrativo",
    "61" = "61-Alta da m\u00e3e/pu\u00e9rpera e do rec\u00e9m-nascido",
    "17" = "17-Alta da m\u00e3e/pu\u00e9rpera e do rec\u00e9m-nascido",
    "62" = "62-Alta da m\u00e3e/pu\u00e9rpera e perman\u00eancia rec\u00e9m-nascido",
    "13" = "13-Alta da m\u00e3e/pu\u00e9rpera e perman\u00eancia rec\u00e9m-nascido",
    "63" = "63-Alta da m\u00e3e/pu\u00e9rpera e \u00f3bito do rec\u00e9m-nascido",
    "64" = "64-Alta da m\u00e3e/pu\u00e9rpera com \u00f3bito fetal",
    "65" = "65-\u00d3bito da gestante e do concepto",
    "66" = "66-\u00d3bito da m\u00e3e/pu\u00e9rpera e alta do rec\u00e9m-nascido",
    "67" = "67-\u00d3bito da m\u00e3e/pu\u00e9rpera e perman\u00eancia rec\u00e9m-nascido"
  )

  type_data = tolower(trimws(type_data))
  #> Indicadores-------
  labels_indicadores = c(
    0, "Tempo M\u00e9dio de Perman\u00eancia Cir\u00fargica",
    0, "Tempo M\u00e9dio de Perman\u00eancia Clinica",
    0, "Tempo M\u00e9dio de Perman\u00eancia Hospitalar",
    0, "Giro de Leito da Produ\u00e7\u00e3o Hospitalar",
    0, "Taxa de Ces\u00e1rea",
    0, "Taxa de Ocupa\u00e7\u00e3o Hospitalar",
    0, "Taxa de Ocupa\u00e7\u00e3o de UTI",
    1, "N\u00famero de Cirurgias Apresentadas",
    1, "N\u00famero de Interna\u00e7\u00f5es Hospitalares",
    1, "N\u00famero dias Perman\u00eancia hosp.",
    1, "N\u00famero motivos sa\u00edda hosp.",
    1, "N\u00famero dias Perman\u00eancia clinica",
    1, "N\u00famero motivos sa\u00edda clinica",
    1, "N\u00famero dias Perman\u00eancia cirurgica",
    1, "N\u00famero motivos sa\u00edda cirurgica",
    1, "N\u00famero partos cesareos",
    1, "N\u00famero partos total",
    1, "N\u00famero dias em UTI",
    1, "N\u00famero leitos UTI",
    1, "N\u00famero leitos hosp. sem leitos hosp. dia"
  )

  #> IF ---------------
  if (type_data == "cnes") {
    #ADD a coluna com o nome dos Hospitais
    dados = dados %>%
      dplyr::mutate(
        nome_CNES = dplyr::recode(as.character(cnes), !!!labels_cnes),
      ) %>% dplyr::relocate(nome_CNES, .before = cnes)
  }
  else if (type_data == "leitos") {
    dados = dados %>%
      dplyr::mutate(
        nome_tipo_leito = dplyr::recode(as.character(cod_tipo_leito),
                                        !!!labels_tipo_leito),
        nome_especialidade_leito = dplyr::recode(
          as.character(cod_especialidade_leito), !!!labels_especialidade_leito)
      ) %>%
      dplyr::relocate(nome_tipo_leito, .before = cod_tipo_leito) %>%
      dplyr::relocate(nome_especialidade_leito, .before = cod_especialidade_leito)
  }
  else if (type_data == "equipamentos") {
   dados <-dados %>%
      dplyr::mutate(
        nome_tipo_equipamento = dplyr::recode(
          as.character(cod_tipo_equipamento), !!!labels_tipo_equipamento),
        nome_equipamento = dplyr::recode(
          as.character(cod_equipamento), !!!labels_equipamento)
      ) %>%
      dplyr::relocate(nome_tipo_equipamento, .before = cod_tipo_equipamento) %>%
      dplyr::relocate(nome_equipamento, .before = cod_equipamento)

  }
  else if (type_data == "habilitacao") {
   dados =dados %>%
      dplyr::mutate(
        nome_habilitacao = dplyr::recode(
          as.character(cod_habilitacao), !!!labels_cod_habilitacao)
      ) %>%
      dplyr::relocate(nome_habilitacao, .before = cod_habilitacao)
  }
  else if (type_data == "tab_grupo_procedimentos") {
    dados <- tibble::tibble(
      cod_grupo_procedimento = as.integer(names(labels_grupos_procedimentos)),
      nome_grupo_procedimento = unname(labels_grupos_procedimentos)
    )
  }
  else if (type_data == "tab_cnes") {
    dados <- tibble::tibble(
      cnes = names(labels_cnes),
      nome_cnes = unname(labels_cnes),
      sigla_cnes = unname(labels_sicla_cnes)
    )
  }
  else if (type_data == "tab_equipamentos") {
    dados <- tibble::tibble(
      cod_equipamento = as.integer(names(labels_equipamento)),
      nome_equipamento = unname(labels_equipamento)
    )
  }
  else if (type_data == "tab_tipo_equipamentos") {
    dados <- tibble::tibble(
      cod_tipo_equipamento = as.integer(names(labels_tipo_equipamento)),
      nome_tipo_equipamento = unname(labels_tipo_equipamento)
    )
  }
  else if (type_data == "tab_habilitacao") {
    dados <- tibble::tibble(
      cod_habilitacao = as.integer(names(labels_cod_habilitacao)),
      nome_habilitacao = unname(labels_cod_habilitacao)
    )
  }
  else if (type_data == "tab_tipo_leito") {
    dados <- tibble::tibble(
      cod_tipo_leito = as.integer(names(labels_tipo_leito)),
      nome_tipo_leito = unname(labels_tipo_leito)
    )
  }
  else if (type_data == "tab_especialidade_leito") {
    dados <- tibble::tibble(
      cod_especialidade_leito = as.integer(names(labels_especialidade_leito)),
      nome_especialidade_leito = unname(labels_especialidade_leito)
    )
  }
  else if (type_data == "tab_motivo_saida_permanencia") {
    dados <- tibble::tibble(
      cod_motivo_saida_ou_permanencia =
        as.integer(names(labels_motivo_saida_permanencia)),
      nome_motivo_saida_permanencia = unname(labels_motivo_saida_permanencia)
    )
  }
  else if (type_data == "d_calendario"){
    # Defina o intervalo de datas desejado
    data_inicio <- as.Date("2019-01-01")
    data_fim <- as.Date("2025-12-01")

    # Cria a tabela d_calendario
    dados <-
      tibble::tibble(data = seq(data_inicio, data_fim, by = "month")) %>%
      dplyr::mutate(
        ano = as.integer(lubridate::year(data)),
        mes = as.integer(lubridate::month(data)),
        mes_nome = as.character(lubridate::month(data, label = TRUE, abbr = FALSE)),
        key_data = as.integer(sprintf("%04d%02d", ano, mes))
      ) %>%
      dplyr::relocate(key_data, .before = 1)
  }
  else if (type_data == "name_indicadores"){
    dados <- data.frame(
      indicador_name =
        labels_indicadores[seq(2,length(labels_indicadores), by=2)],
      #Se o indicador é absoluto ou nao
      indicador_absoluto =
        as.integer(labels_indicadores[seq(1,length(labels_indicadores), by=2)]),
      stringsAsFactors = FALSE
    )
  }
  return(dados)
}
